package com.brainx.server.core;

import java.time.Instant;
import java.util.List;
import java.util.Map;

public record ChatSessionRecord(
    String id,
    String title,
    String parentSessionId,
    String rootSessionId,
    String forkedFromSessionId,
    String workspaceId,
    String workspaceName,
    String currentWorkspace,
    String agentId,
    String agentName,
    String branchId,
    String branchName,
    String skillName,
    String clientName,
    String runId,
    String runStatus,
    List<Map<String, Object>> todos,
    List<Map<String, Object>> terminals,
    List<Map<String, Object>> subagents,
    Map<String, Map<String, Object>> toolStates,
    Map<String, Object> contextBudget,
    List<Map<String, Object>> availableModels,
    String activeModelName,
    List<Map<String, Object>> queuedInputs,
    List<Map<String, Object>> timelineNotices,
    Instant createdAt,
    Instant updatedAt,
    List<Map<String, Object>> messages
) {
  public ChatSessionRecord withRun(String nextRunId, String nextRunStatus, Instant nextUpdatedAt) {
    return new ChatSessionRecord(
        id,
        title,
        parentSessionId,
        rootSessionId,
        forkedFromSessionId,
        workspaceId,
        workspaceName,
        currentWorkspace,
        agentId,
        agentName,
        branchId,
        branchName,
        skillName,
        clientName,
        nextRunId,
        nextRunStatus,
        todos,
        terminals,
        subagents,
        toolStates,
        contextBudget,
        availableModels,
        activeModelName,
        queuedInputs,
        timelineNotices,
        createdAt,
        nextUpdatedAt,
        messages
    );
  }

  public ChatSessionRecord withMessages(List<Map<String, Object>> nextMessages, String nextRunStatus, Instant nextUpdatedAt) {
    return new ChatSessionRecord(
        id,
        title,
        parentSessionId,
        rootSessionId,
        forkedFromSessionId,
        workspaceId,
        workspaceName,
        currentWorkspace,
        agentId,
        agentName,
        branchId,
        branchName,
        skillName,
        clientName,
        runId,
        nextRunStatus,
        todos,
        terminals,
        subagents,
        toolStates,
        contextBudget,
        availableModels,
        activeModelName,
        queuedInputs,
        timelineNotices,
        createdAt,
        nextUpdatedAt,
        List.copyOf(nextMessages)
    );
  }

  public ChatSessionRecord withToolStates(Map<String, Map<String, Object>> nextToolStates) {
    return new ChatSessionRecord(
        id,
        title,
        parentSessionId,
        rootSessionId,
        forkedFromSessionId,
        workspaceId,
        workspaceName,
        currentWorkspace,
        agentId,
        agentName,
        branchId,
        branchName,
        skillName,
        clientName,
        runId,
        runStatus,
        todos,
        terminals,
        subagents,
        Map.copyOf(nextToolStates),
        contextBudget,
        availableModels,
        activeModelName,
        queuedInputs,
        timelineNotices,
        createdAt,
        updatedAt,
        messages
    );
  }

  public ChatSessionRecord withResponseState(
      Map<String, Map<String, Object>> nextToolStates,
      Map<String, Object> nextContextBudget,
      List<Map<String, Object>> nextAvailableModels,
      String nextActiveModelName
  ) {
    return new ChatSessionRecord(
        id,
        title,
        parentSessionId,
        rootSessionId,
        forkedFromSessionId,
        workspaceId,
        workspaceName,
        currentWorkspace,
        agentId,
        agentName,
        branchId,
        branchName,
        skillName,
        clientName,
        runId,
        runStatus,
        todos,
        terminals,
        subagents,
        Map.copyOf(nextToolStates),
        Map.copyOf(nextContextBudget),
        List.copyOf(nextAvailableModels),
        nextActiveModelName,
        queuedInputs,
        timelineNotices,
        createdAt,
        updatedAt,
        messages
    );
  }

  public ChatSessionRecord withState(
      List<Map<String, Object>> nextTodos,
      List<Map<String, Object>> nextTerminals,
      List<Map<String, Object>> nextSubagents,
      String nextRunStatus,
      Instant nextUpdatedAt
  ) {
    return new ChatSessionRecord(
        id,
        title,
        parentSessionId,
        rootSessionId,
        forkedFromSessionId,
        workspaceId,
        workspaceName,
        currentWorkspace,
        agentId,
        agentName,
        branchId,
        branchName,
        skillName,
        clientName,
        runId,
        nextRunStatus,
        List.copyOf(nextTodos),
        List.copyOf(nextTerminals),
        List.copyOf(nextSubagents),
        toolStates,
        contextBudget,
        availableModels,
        activeModelName,
        queuedInputs,
        timelineNotices,
        createdAt,
        nextUpdatedAt,
        messages
    );
  }

  public ChatSessionRecord withCurrentWorkspace(String nextCurrentWorkspace, Instant nextUpdatedAt) {
    return new ChatSessionRecord(
        id,
        title,
        parentSessionId,
        rootSessionId,
        forkedFromSessionId,
        workspaceId,
        workspaceName,
        nextCurrentWorkspace,
        agentId,
        agentName,
        branchId,
        branchName,
        skillName,
        clientName,
        runId,
        runStatus,
        todos,
        terminals,
        subagents,
        toolStates,
        contextBudget,
        availableModels,
        activeModelName,
        queuedInputs,
        timelineNotices,
        createdAt,
        nextUpdatedAt,
        messages
    );
  }

  public ChatSessionRecord withQueuedInputs(List<Map<String, Object>> nextQueuedInputs, Instant nextUpdatedAt) {
    return new ChatSessionRecord(
        id,
        title,
        parentSessionId,
        rootSessionId,
        forkedFromSessionId,
        workspaceId,
        workspaceName,
        currentWorkspace,
        agentId,
        agentName,
        branchId,
        branchName,
        skillName,
        clientName,
        runId,
        runStatus,
        todos,
        terminals,
        subagents,
        toolStates,
        contextBudget,
        availableModels,
        activeModelName,
        List.copyOf(nextQueuedInputs),
        timelineNotices,
        createdAt,
        nextUpdatedAt,
        messages
    );
  }

  public ChatSessionRecord withTitle(String nextTitle, Instant nextUpdatedAt) {
    return new ChatSessionRecord(
        id,
        nextTitle,
        parentSessionId,
        rootSessionId,
        forkedFromSessionId,
        workspaceId,
        workspaceName,
        currentWorkspace,
        agentId,
        agentName,
        branchId,
        branchName,
        skillName,
        clientName,
        runId,
        runStatus,
        todos,
        terminals,
        subagents,
        toolStates,
        contextBudget,
        availableModels,
        activeModelName,
        queuedInputs,
        timelineNotices,
        createdAt,
        nextUpdatedAt,
        messages
    );
  }

  public ChatSessionRecord withTimelineNotices(List<Map<String, Object>> nextTimelineNotices, Instant nextUpdatedAt) {
    return new ChatSessionRecord(
        id,
        title,
        parentSessionId,
        rootSessionId,
        forkedFromSessionId,
        workspaceId,
        workspaceName,
        currentWorkspace,
        agentId,
        agentName,
        branchId,
        branchName,
        skillName,
        clientName,
        runId,
        runStatus,
        todos,
        terminals,
        subagents,
        toolStates,
        contextBudget,
        availableModels,
        activeModelName,
        queuedInputs,
        List.copyOf(nextTimelineNotices),
        createdAt,
        nextUpdatedAt,
        messages
    );
  }

  public ChatSessionRecord withMessagesAndTimelineNotices(
      List<Map<String, Object>> nextMessages,
      List<Map<String, Object>> nextTimelineNotices,
      String nextRunStatus,
      Instant nextUpdatedAt
  ) {
    return new ChatSessionRecord(
        id,
        title,
        parentSessionId,
        rootSessionId,
        forkedFromSessionId,
        workspaceId,
        workspaceName,
        currentWorkspace,
        agentId,
        agentName,
        branchId,
        branchName,
        skillName,
        clientName,
        runId,
        nextRunStatus,
        todos,
        terminals,
        subagents,
        toolStates,
        contextBudget,
        availableModels,
        activeModelName,
        queuedInputs,
        List.copyOf(nextTimelineNotices),
        createdAt,
        nextUpdatedAt,
        List.copyOf(nextMessages)
    );
  }
}
